# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-22 07:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('gender', models.CharField(max_length=30)),
                ('age', models.CharField(max_length=30)),
                ('experience', models.CharField(max_length=4000)),
                ('emotion_scale', models.CharField(choices=[('1', '1 - Not at all happy'), ('2', '2 - Neutral'), ('3', '3 - Little Happy'), ('4', '4 - Moderately Happy'), ('5', '5 - Very Happy')], max_length=1)),
                ('ans_1', models.CharField(max_length=30)),
                ('ans_2', models.CharField(choices=[('1', 'Circle in middle of figure A is bigger than circle in middle of figure B'), ('2', 'Circle in middle of figure B is bigger than circle in middle of figure A'), ('3', 'Both the circle in the middle are of the same size')], max_length=1)),
                ('ans_3', models.CharField(max_length=30)),
                ('ans_4', models.CharField(max_length=30)),
            ],
        ),
    ]
